"""
MA TRẬN KỊCH BẢN KIỂM THỬ BACKEND (TEST CASES SPECIFICATION MATRIX)
Được trích xuất từ file yêu cầu nghiệp vụ: HỆ THỐNG BÁN HÀNG & KHO_ TTCS_T926_K13C4.xlsx
Bao phủ toàn diện 10 User Stories (S1-01 -> S1-10) của Sprint 1 theo chuẩn SCRUM.
"""

from typing import List, Dict, Any

DANH_SACH_TEST_CASES_CHUAN: List[Dict[str, Any]] = [
    # =========================================================================
    # GÓI 1: PKG-01 - XÁC THỰC ĐĂNG NHẬP & KHÓA 15 PHÚT (Story S1-01 / SCRUM-287)
    # =========================================================================
    {
        "stt": 1,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-01",
        "name": "Bắt lỗi thiếu trường bắt buộc khi đăng nhập",
        "priority": "Critical",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/login",
        "payload": "{}",
        "expected": "HTTP 422 Unprocessable Entity - Báo lỗi thiếu username và password",
        "notes": "Kiểm tra ràng buộc dữ liệu đầu vào theo Pydantic schema",
    },
    {
        "stt": 2,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-02",
        "name": "Đăng nhập với tài khoản không tồn tại trong hệ thống",
        "priority": "High",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "non_existent_user_999", "password": "WrongPassword@123"}',
        "expected": "HTTP 401 Unauthorized - Thông báo chung 'Tên đăng nhập hoặc mật khẩu không chính xác.'",
        "notes": "Chống kỹ thuật User Enumeration Attack, không tiết lộ tài khoản tồn tại",
    },
    {
        "stt": 3,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-03",
        "name": "Đăng nhập đúng tài khoản nhưng sai mật khẩu",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "sales_mgr", "password": "WrongPassword@123"}',
        "expected": "HTTP 401 Unauthorized - Thông báo chung 'Tên đăng nhập hoặc mật khẩu không chính xác.'",
        "notes": "Tăng số lần đăng nhập sai (failed_login_attempts)",
    },
    {
        "stt": 4,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-04",
        "name": "Khóa tạm thời 15 phút sau 5 lần nhập sai liên tiếp",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "TEST_TMP_LOCK_USER", "password": "WrongPassword@123"}',
        "expected": "HTTP 403 Forbidden - Thông báo 'Tài khoản tạm thời bị khóa trong 15 phút do nhập sai nhiều lần.'",
        "notes": "SCRUM-287: Khóa 15 phút sau 5 lần sai liên tiếp",
    },
    {
        "stt": 5,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-05",
        "name": "Đăng nhập thành công với tài khoản Quản trị hệ thống (Admin)",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "admin", "password": "Admin@123456"}',
        "expected": "HTTP 200 OK - Trả về access_token JWT Bearer và role Admin",
        "notes": "Xác thực vai trò Quản trị hệ thống",
    },
    {
        "stt": 6,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-06",
        "name": "Đăng nhập thành công với tài khoản Quản lý kinh doanh (Sales Manager)",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "sales_mgr", "password": "SalesMgr@1234"}',
        "expected": "HTTP 200 OK - Trả về access_token và role Sales Manager",
        "notes": "Xác thực vai trò Quản lý kinh doanh",
    },
    {
        "stt": 7,
        "pkg_id": "PKG-01",
        "story_id": "S1-01",
        "tc_id": "TC-AUTH-07",
        "name": "Đăng nhập thành công với tài khoản Đại lý (Customer)",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "customer", "password": "Customer@1234"}',
        "expected": "HTTP 200 OK - Trả về access_token và role Customer",
        "notes": "Xác thực vai trò Đại lý / Khách hàng",
    },

    # =========================================================================
    # GÓI 2: PKG-02 - DUY TRÌ PHIÊN, ĐĂNG XUẤT & THÔNG TIN CÁ NHÂN (S1-02 & S1-06)
    # =========================================================================
    {
        "stt": 8,
        "pkg_id": "PKG-02",
        "story_id": "S1-02",
        "tc_id": "TC-SESS-01",
        "name": "Gia hạn phiên khi không truyền Authorization Bearer header",
        "priority": "Medium",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/refresh",
        "payload": "None",
        "expected": "HTTP 401 Unauthorized - Từ chối khi không có token",
        "notes": "Kiểm tra cơ chế Deny by default",
    },
    {
        "stt": 9,
        "pkg_id": "PKG-02",
        "story_id": "S1-02",
        "tc_id": "TC-SESS-02",
        "name": "Gia hạn phiên tự động thành công khi người dùng đang hoạt động",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/refresh",
        "payload": "Headers: Bearer <token_hợp_lệ>",
        "expected": "HTTP 200 OK - Trả về token mới và thông tin người dùng",
        "notes": "SCRUM-199: Phiên gia hạn tự động khi còn hiệu lực",
    },
    {
        "stt": 10,
        "pkg_id": "PKG-02",
        "story_id": "S1-02",
        "tc_id": "TC-SESS-03",
        "name": "Đăng xuất an toàn vô hiệu hóa phiên phía máy chủ",
        "priority": "High",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/logout",
        "payload": "Headers: Bearer <token_hợp_lệ>",
        "expected": "HTTP 200 OK - 'Đăng xuất thành công. Phiên đăng nhập đã bị vô hiệu hóa phía máy chủ.'",
        "notes": "SCRUM-199: Server tăng token_version để hủy phiên ngay lập tức",
    },
    {
        "stt": 11,
        "pkg_id": "PKG-02",
        "story_id": "S1-02",
        "tc_id": "TC-SESS-04",
        "name": "Sử dụng lại token cũ sau khi đã đăng xuất bị từ chối",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/me",
        "payload": "Headers: Bearer <token_vừa_đăng_xuất>",
        "expected": "HTTP 401 Unauthorized - 'Phiên đăng nhập đã bị thu hồi...'",
        "notes": "SCRUM-199: Chống tấn công Replay Attack bằng token cũ",
    },
    {
        "stt": 12,
        "pkg_id": "PKG-02",
        "story_id": "S1-06",
        "tc_id": "TC-NAV-01",
        "name": "Lấy thông tin người dùng đang đăng nhập khi không có token",
        "priority": "Medium",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/me",
        "payload": "None",
        "expected": "HTTP 401 Unauthorized - Yêu cầu xác thực",
        "notes": "Bảo vệ endpoint thông tin cá nhân",
    },
    {
        "stt": 13,
        "pkg_id": "PKG-02",
        "story_id": "S1-06",
        "tc_id": "TC-NAV-02",
        "name": "Lấy thông tin người dùng hiển thị tên, vai trò và kho phụ trách",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/auth/me",
        "payload": "Headers: Bearer <token_thủ_kho>",
        "expected": "HTTP 200 OK - Trả về full_name, role, assigned_warehouse",
        "notes": "SCRUM-203: Hiển thị tên, vai trò và kho hoặc địa bàn đang làm việc",
    },

    # =========================================================================
    # GÓI 3: PKG-03 - QUẢN LÝ MẬT KHẨU: QUÊN & ĐỔI MẬT KHẨU (Story S1-03 & S1-04)
    # =========================================================================
    {
        "stt": 14,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-01",
        "name": "Quên mật khẩu: Kiểm tra email sai định dạng",
        "priority": "Medium",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/forgot-password",
        "payload": '{"email": "not-an-email"}',
        "expected": "HTTP 422 Unprocessable Entity - Báo lỗi định dạng email",
        "notes": "Validate EmailStr bằng Pydantic",
    },
    {
        "stt": 15,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-02",
        "name": "Quên mật khẩu: Email không tồn tại vẫn trả thông báo chung an toàn",
        "priority": "High",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/forgot-password",
        "payload": '{"email": "khong_ton_tai_999@warehouse.local"}',
        "expected": "HTTP 200 OK - Thông báo 'Nếu email tồn tại trong hệ thống, hướng dẫn đặt lại...'",
        "notes": "SCRUM-200: Email không tồn tại vẫn hiển thị cùng một thông báo",
    },
    {
        "stt": 16,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-03",
        "name": "Quên mật khẩu: Yêu cầu đặt lại mật khẩu thành công với email hợp lệ",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/forgot-password",
        "payload": '{"email": "customer@warehouse.local"}',
        "expected": "HTTP 200 OK - Sinh token đặt lại có hiệu lực 30 phút trong DB",
        "notes": "SCRUM-200: Nhập email nhận được liên kết đặt lại có hiệu lực 30 phút",
    },
    {
        "stt": 17,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-04",
        "name": "Đặt lại mật khẩu: Sử dụng token không hợp lệ hoặc không tồn tại",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/reset-password",
        "payload": '{"token": "invalid_fake_token_123", "new_password": "NewPassword@123"}',
        "expected": "HTTP 400 Bad Request - 'Liên kết đặt lại mật khẩu không hợp lệ hoặc đã được sử dụng.'",
        "notes": "Chặn token giả mạo",
    },
    {
        "stt": 18,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-05",
        "name": "Đặt lại mật khẩu: Mật khẩu mới yếu (< 8 ký tự hoặc thiếu số/chữ)",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/reset-password",
        "payload": '{"token": "valid_token", "new_password": "123"}',
        "expected": "HTTP 422 Unprocessable Entity - Bắt lỗi độ mạnh mật khẩu (tối thiểu 8 ký tự, có chữ và số)",
        "notes": "SCRUM-200 / SCRUM-307: Chính sách độ mạnh mật khẩu",
    },
    {
        "stt": 19,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-06",
        "name": "Đặt lại mật khẩu thành công với token hợp lệ còn hạn 30 phút",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/reset-password",
        "payload": '{"token": "<token_thật>", "new_password": "NewResetPass@2026"}',
        "expected": "HTTP 200 OK - 'Đặt lại mật khẩu thành công. Vui lòng đăng nhập bằng mật khẩu mới.'",
        "notes": "Cập nhật mật khẩu mới, hủy token và tăng token_version",
    },
    {
        "stt": 20,
        "pkg_id": "PKG-03",
        "story_id": "S1-03",
        "tc_id": "TC-PWD-07",
        "name": "Thử sử dụng lại token đặt lại mật khẩu lần 2 bị từ chối",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/reset-password",
        "payload": '{"token": "<token_vừa_dùng>", "new_password": "AnotherPass@2026"}',
        "expected": "HTTP 400 Bad Request - 'Liên kết đặt lại mật khẩu không hợp lệ hoặc đã được sử dụng.'",
        "notes": "SCRUM-200: Liên kết chỉ dùng được một lần",
    },
    {
        "stt": 21,
        "pkg_id": "PKG-03",
        "story_id": "S1-04",
        "tc_id": "TC-CHGPWD-01",
        "name": "Đổi mật khẩu khi chưa xác thực Bearer token",
        "priority": "Medium",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/change-password",
        "payload": '{"old_password": "Old@123", "new_password": "NewPassword@123"}',
        "expected": "HTTP 401 Unauthorized - Yêu cầu phiên đăng nhập",
        "notes": "Bảo vệ endpoint đổi mật khẩu",
    },
    {
        "stt": 22,
        "pkg_id": "PKG-03",
        "story_id": "S1-04",
        "tc_id": "TC-CHGPWD-02",
        "name": "Đổi mật khẩu: Mật khẩu cũ không chính xác",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/change-password",
        "payload": '{"old_password": "WrongOldPassword@123", "new_password": "NewPassword@123"}',
        "expected": "HTTP 400 Bad Request - 'Mật khẩu cũ không chính xác.'",
        "notes": "SCRUM-201: Bắt buộc nhập mật khẩu hiện tại",
    },
    {
        "stt": 23,
        "pkg_id": "PKG-03",
        "story_id": "S1-04",
        "tc_id": "TC-CHGPWD-03",
        "name": "Đổi mật khẩu: Mật khẩu mới trùng với mật khẩu hiện tại",
        "priority": "Medium",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/change-password",
        "payload": '{"old_password": "SamePassword@123", "new_password": "SamePassword@123"}',
        "expected": "HTTP 400 Bad Request - 'Mật khẩu mới không được trùng với mật khẩu hiện tại.'",
        "notes": "Chính sách an toàn mật khẩu chống đặt lại mật khẩu cũ",
    },
    {
        "stt": 24,
        "pkg_id": "PKG-03",
        "story_id": "S1-04",
        "tc_id": "TC-CHGPWD-04",
        "name": "Đổi mật khẩu: Mật khẩu mới không đủ độ mạnh (< 8 ký tự hoặc thiếu chữ/số)",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/auth/change-password",
        "payload": '{"old_password": "CurrentPass@123", "new_password": "short"}',
        "expected": "HTTP 422 Unprocessable Entity - Bắt lỗi độ mạnh mật khẩu",
        "notes": "SCRUM-201: Mật khẩu mới tối thiểu 8 ký tự, có chữ và số",
    },
    {
        "stt": 25,
        "pkg_id": "PKG-03",
        "story_id": "S1-04",
        "tc_id": "TC-CHGPWD-05",
        "name": "Đổi mật khẩu thành công và thu hồi toàn bộ các phiên đăng nhập khác",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/change-password",
        "payload": '{"old_password": "CurrentPass@123", "new_password": "NewStrongPass@2026"}',
        "expected": "HTTP 200 OK - 'Đổi mật khẩu thành công. Toàn bộ các phiên đăng nhập khác đã được thu hồi.'",
        "notes": "SCRUM-201: Đổi xong thu hồi các phiên đăng nhập khác qua token_version",
    },

    # =========================================================================
    # GÓI 4: PKG-04 - PHÂN QUYỀN VAI TRÒ (RBAC) & BẢO MẬT GIÁ VỐN (Story S1-05)
    # =========================================================================
    {
        "stt": 26,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-01",
        "name": "Bảo mật giá vốn: Đại lý (Customer) truy cập báo cáo giá vốn bị chặn",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/financial/cost-and-margin",
        "payload": "Headers: Bearer <token_customer>",
        "expected": "HTTP 403 Forbidden - 'Bạn không có quyền thực hiện hành động này...'",
        "notes": "SCRUM-202: Giá vốn và biên lợi nhuận chỉ lộ ra với vai trò Quản lý kinh doanh",
    },
    {
        "stt": 27,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-02",
        "name": "Bảo mật giá vốn: Nhân viên kinh doanh (Sales Rep) truy cập giá vốn bị chặn",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/financial/cost-and-margin",
        "payload": "Headers: Bearer <token_sales_rep>",
        "expected": "HTTP 403 Forbidden - Bị chặn ở tầng server",
        "notes": "SCRUM-202: Nhân viên kinh doanh không được xem giá vốn",
    },
    {
        "stt": 28,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-03",
        "name": "Bảo mật giá vốn: Thủ kho (Warehouse) truy cập giá vốn bị chặn",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/financial/cost-and-margin",
        "payload": "Headers: Bearer <token_warehouse>",
        "expected": "HTTP 403 Forbidden - Bị chặn ở tầng server",
        "notes": "SCRUM-202: Thủ kho không xem được giá vốn",
    },
    {
        "stt": 29,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-04",
        "name": "Quản lý kinh doanh (Sales Manager) xem báo cáo giá vốn & biên lợi nhuận",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/auth/financial/cost-and-margin",
        "payload": "Headers: Bearer <token_sales_mgr>",
        "expected": "HTTP 200 OK - Trả về danh sách SKU, cost_price, selling_price, profit_margin",
        "notes": "SCRUM-202: Giá vốn và biên lợi nhuận hiển thị đúng cho Quản lý kinh doanh",
    },
    {
        "stt": 30,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-05",
        "name": "Quản trị viên (Admin) xem báo cáo giá vốn & biên lợi nhuận",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/auth/financial/cost-and-margin",
        "payload": "Headers: Bearer <token_admin>",
        "expected": "HTTP 200 OK - Admin có quyền truy cập toàn bộ hệ thống",
        "notes": "Admin toàn quyền quản trị",
    },
    {
        "stt": 31,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-06",
        "name": "Guard phân quyền: Nhân viên kinh doanh truy cập phân hệ Quản lý Kho bị chặn",
        "priority": "High",
        "test_type": "Security",
        "endpoint": "GET /api/v1/auth/demo/warehouse-only",
        "payload": "Headers: Bearer <token_sales_rep>",
        "expected": "HTTP 403 Forbidden - Từ chối vai trò Sales Rep",
        "notes": "SCRUM-310: Phân cách quyền giữa bộ phận Bán hàng và bộ phận Kho",
    },
    {
        "stt": 32,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-07",
        "name": "Guard phân quyền: Thủ kho truy cập phân hệ Quản lý Kho thành công",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/auth/demo/warehouse-only",
        "payload": "Headers: Bearer <token_warehouse>",
        "expected": "HTTP 200 OK - 'Bạn đã truy cập thành công phân hệ Quản lý Kho...'",
        "notes": "SCRUM-310: Thủ kho được phép truy cập",
    },
    {
        "stt": 33,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-08",
        "name": "Lấy danh sách 7 vai trò hệ thống đầy đủ",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/roles",
        "payload": "None",
        "expected": "HTTP 200 OK - Danh sách có đủ các vai trò: ADMIN, SALES, WAREHOUSE, ACCOUNTANT...",
        "notes": "SCRUM-202: Khai báo được quyền cho từng vai trò trong bảy vai trò nghiệp vụ",
    },
    {
        "stt": 34,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-09",
        "name": "Lấy danh sách quyền hệ thống có thể lọc theo module",
        "priority": "Medium",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/permissions?module=users",
        "payload": "Query: module=users",
        "expected": "HTTP 200 OK - Trả về danh sách quyền của module users (user:view, user:create...)",
        "notes": "Hệ thống quyền hạn chi tiết",
    },
    {
        "stt": 35,
        "pkg_id": "PKG-04",
        "story_id": "S1-05",
        "tc_id": "TC-RBAC-10",
        "name": "Lấy chi tiết vai trò theo ID",
        "priority": "Medium",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/roles/1",
        "payload": "Path: role_id=1",
        "expected": "HTTP 200 OK - Trả về chi tiết vai trò kèm danh sách permissions",
        "notes": "Kiểm tra xem quyền gán cho vai trò",
    },

    # =========================================================================
    # GÓI 5: PKG-05 - QUẢN LÝ NGƯỜI DÙNG & GÁN VAI TRÒ (Story S1-08 & S1-09)
    # =========================================================================
    {
        "stt": 36,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-01",
        "name": "Người dùng không phải Quản trị viên gọi API tạo tài khoản bị từ chối",
        "priority": "High",
        "test_type": "Security",
        "endpoint": "POST /api/v1/users",
        "payload": "Headers: Bearer <token_customer>, Body: {...}",
        "expected": "HTTP 403 Forbidden - Chỉ Quản trị hệ thống (Admin) mới có quyền",
        "notes": "Bảo vệ endpoint tạo tài khoản",
    },
    {
        "stt": 37,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-02",
        "name": "Tạo người dùng: Bắt lỗi thiếu username hoặc email bắt buộc",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/users",
        "payload": '{"full_name": "Test Missing Fields"}',
        "expected": "HTTP 422 Unprocessable Entity - Báo thiếu username và email",
        "notes": "Validation Pydantic schema",
    },
    {
        "stt": 38,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-03",
        "name": "Tạo người dùng: Bắt lỗi địa chỉ email không đúng định dạng",
        "priority": "Medium",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "test_inv_email", "email": "wrong-format-email"}',
        "expected": "HTTP 422 Unprocessable Entity - Báo lỗi định dạng email",
        "notes": "Validation EmailStr",
    },
    {
        "stt": 39,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-04",
        "name": "Admin tạo tài khoản người dùng mới thành công với mật khẩu tự sinh tạm",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "TEST_TMP_NVKD_01", "email": "test_tmp_nvkd01@warehouse.local", "role": "Sales Rep", "full_name": "Trần Văn Kinh Doanh"}',
        "expected": "HTTP 201 Created - Trả về UserResponse, must_change_password=True",
        "notes": "SCRUM-205: Tạo tài khoản gửi email kích hoạt kèm mật khẩu tạm",
    },
    {
        "stt": 40,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-05",
        "name": "Tạo người dùng: Trùng tên đăng nhập (username) bị từ chối kèm thông báo cụ thể",
        "priority": "Critical",
        "test_type": "Business",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "admin", "email": "unique_email_test@warehouse.local", "role": "Customer"}',
        "expected": "HTTP 400 Bad Request - 'Tên đăng nhập 'admin' đã tồn tại trong hệ thống. Vui lòng chọn tên khác.'",
        "notes": "SCRUM-205: Tài khoản trùng bị từ chối kèm thông báo cụ thể",
    },
    {
        "stt": 41,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-06",
        "name": "Tạo người dùng: Trùng địa chỉ email bị từ chối kèm thông báo cụ thể",
        "priority": "Critical",
        "test_type": "Business",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "unique_usr_test", "email": "customer@warehouse.local", "role": "Customer"}',
        "expected": "HTTP 400 Bad Request - 'Địa chỉ email 'customer@warehouse.local' đã được đăng ký...'",
        "notes": "SCRUM-205: Kiểm tra tính duy nhất của email",
    },
    {
        "stt": 42,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-07",
        "name": "Tìm kiếm tài khoản người dùng theo từ khóa (tên, username hoặc số điện thoại)",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/users?q=admin",
        "payload": "Query: q=admin",
        "expected": "HTTP 200 OK - Trả về danh sách chứa tài khoản khớp từ khóa",
        "notes": "SCRUM-205: Tìm theo tên, tài khoản, số điện thoại",
    },
    {
        "stt": 43,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-08",
        "name": "Lọc danh sách tài khoản theo vai trò và trạng thái",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/users?role=Customer&is_active=true",
        "payload": "Query: role=Customer&is_active=true",
        "expected": "HTTP 200 OK - Chỉ trả về các tài khoản role Customer đang hoạt động",
        "notes": "SCRUM-205: Lọc theo vai trò và trạng thái",
    },
    {
        "stt": 44,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-09",
        "name": "Phân trang danh sách tài khoản người dùng (mặc định 20 dòng)",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "GET /api/v1/users",
        "payload": "Default pagination params",
        "expected": "HTTP 200 OK - page=1, page_size=20, items, total, total_pages",
        "notes": "SCRUM-205: Danh sách phân trang, mặc định 20 dòng",
    },
    {
        "stt": 45,
        "pkg_id": "PKG-05",
        "story_id": "S1-08",
        "tc_id": "TC-USER-10",
        "name": "Chỉnh sửa thông tin họ tên và số điện thoại người dùng",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "PUT /api/v1/users/{user_id}",
        "payload": '{"full_name": "Nguyễn Văn Đã Cập Nhật", "phone_number": "0987654321"}',
        "expected": "HTTP 200 OK - Trả về UserResponse với thông tin mới đã cập nhật",
        "notes": "Cập nhật hồ sơ tài khoản",
    },
    {
        "stt": 46,
        "pkg_id": "PKG-05",
        "story_id": "S1-09",
        "tc_id": "TC-ROLE-01",
        "name": "Ràng buộc vai trò kho: Tạo tài khoản vai trò Kho nhưng KHÔNG gắn kho bị từ chối",
        "priority": "Critical",
        "test_type": "Business",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "TEST_TMP_KHO_NO_WH", "email": "test_no_wh@warehouse.local", "role": "Warehouse"}',
        "expected": "HTTP 400 Bad Request - 'Người dùng thuộc vai trò kho phải được gắn với ít nhất một kho hoặc địa bàn cụ thể.'",
        "notes": "SCRUM-206: Người dùng thuộc vai trò kho phải gắn với ít nhất một kho cụ thể",
    },
    {
        "stt": 47,
        "pkg_id": "PKG-05",
        "story_id": "S1-09",
        "tc_id": "TC-ROLE-02",
        "name": "Tạo tài khoản vai trò Kho có gắn kho cụ thể thành công",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/users",
        "payload": '{"username": "TEST_TMP_KHO_OK", "email": "test_kho_ok@warehouse.local", "role": "Warehouse", "assigned_warehouse": "Kho Tổng Bình Dương"}',
        "expected": "HTTP 201 Created - Tạo thành công với assigned_warehouse='Kho Tổng Bình Dương'",
        "notes": "SCRUM-206: Hợp lệ khi gắn kho phụ trách",
    },
    {
        "stt": 48,
        "pkg_id": "PKG-05",
        "story_id": "S1-09",
        "tc_id": "TC-ROLE-03",
        "name": "Bảo vệ tài khoản quản trị: Quản trị viên tự thu hồi vai trò Admin của chính mình bị từ chối",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "PUT /api/v1/users/{admin_id}",
        "payload": '{"role": "Customer"}',
        "expected": "HTTP 400 Bad Request - 'Không thể tự thu hồi vai trò quản trị viên của chính mình.'",
        "notes": "SCRUM-206: Không thể tự thu hồi vai trò quản trị của chính mình",
    },

    # =========================================================================
    # GÓI 6: PKG-06 - KHÓA VÀ MỞ KHÓA TÀI KHOẢN (Story S1-10 / SCRUM-207)
    # =========================================================================
    {
        "stt": 49,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-01",
        "name": "Khóa tài khoản: Bắt buộc ghi lý do khóa (reason)",
        "priority": "High",
        "test_type": "Validation",
        "endpoint": "POST /api/v1/users/{user_id}/lock",
        "payload": "{}",
        "expected": "HTTP 422 Unprocessable Entity - Báo thiếu trường reason",
        "notes": "SCRUM-207: Bắt buộc ghi lý do khoá",
    },
    {
        "stt": 50,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-02",
        "name": "Bảo vệ Admin: Quản trị viên tự khóa tài khoản của chính mình bị từ chối",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "POST /api/v1/users/{admin_id}/lock",
        "payload": '{"reason": "Tự khóa thử nghiệm"}',
        "expected": "HTTP 400 Bad Request - 'Không thể tự khóa tài khoản của chính mình.'",
        "notes": "Chống khóa nhầm tài khoản Admin đang thao tác",
    },
    {
        "stt": 51,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-03",
        "name": "Khóa tài khoản Nhân viên kinh doanh kèm cảnh báo bàn giao đại lý phụ trách",
        "priority": "Critical",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/users/{sales_rep_id}/lock",
        "payload": '{"reason": "Nhân viên nghỉ việc từ tháng 10"}',
        "expected": "HTTP 200 OK - session_revoked=True kèm handover_warning cảnh báo bàn giao đại lý",
        "notes": "SCRUM-207: Đại lý do nhân viên bị khoá phụ trách được cảnh báo cần bàn giao",
    },
    {
        "stt": 52,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-04",
        "name": "Tài khoản bị khóa không thể đăng nhập vào hệ thống",
        "priority": "Critical",
        "test_type": "Security",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "TEST_TMP_LOCKED_USER", "password": "Password@123"}',
        "expected": "HTTP 403 Forbidden - 'Tài khoản đã bị vô hiệu hóa. Vui lòng liên hệ quản trị viên.'",
        "notes": "SCRUM-207: Tài khoản bị khoá không đăng nhập được và bị thu hồi phiên đang mở",
    },
    {
        "stt": 53,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-05",
        "name": "Mở khóa tài khoản đã bị khóa thành công",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/users/{user_id}/unlock",
        "payload": "None",
        "expected": "HTTP 200 OK - 'Tài khoản... đã được mở khóa thành công.'",
        "notes": "Khôi phục trạng thái hoạt động is_active=True",
    },
    {
        "stt": 54,
        "pkg_id": "PKG-06",
        "story_id": "S1-10",
        "tc_id": "TC-LOCK-06",
        "name": "Tài khoản đăng nhập lại bình thường sau khi được mở khóa",
        "priority": "High",
        "test_type": "Functional",
        "endpoint": "POST /api/v1/auth/login",
        "payload": '{"username": "TEST_TMP_UNLOCKED_USER", "password": "Password@123"}',
        "expected": "HTTP 200 OK - Đăng nhập thành công và cấp access_token mới",
        "notes": "Hoàn tất chu trình khóa và mở khóa tài khoản",
    },
]
